script: "bundle exec rake spec"
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  #  FIXME: failing native extensions
  #- ruby-head
  #  TODO: investigate failure
  #  This is an arbitrary failure on travis
  #- jruby-18mode
  #- jruby-19mode
  #- jruby-head
  - rbx-18mode
  - rbx-19mode
  - ree
gemfile:
  - gemfiles/mongoid2.gemfile
  - gemfiles/mongoid3.gemfile
  - Gemfile
notifications:
  recipients:
    - andreas@aloop.org
