language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  #  TODO: Refactor deps and dummy rails app to enable the following
  #- jruby-18mode
  #- jruby-19mode ## json error
  #- jruby-head ## json error
  #- rbx-18mode ## sqlite3 error
  #- rbx-19mode ## sqlite3 error
  - ree
notifications:
  recipients:
    - andreas@aloop.org
