script: "bundle exec rake spec"
language: ruby
services: mongodb
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  #  FIXME: failing native extensions
  #- ruby-head
  #  TODO: investigate failure
  #  This is an arbitrary failure on travis
  #- jruby-18mode
  #- jruby-19mode
  #- jruby-head
  - rbx-18mode
  - rbx-19mode
  - ree
gemfile:
  - gemfiles/mongoid2.gemfile
  - gemfiles/mongoid3.gemfile
  - Gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/mongoid3.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/mongoid3.gemfile
    - rvm: rbx-18mode
      gemfile: gemfiles/mongoid3.gemfile
    - rvm: ree
      gemfile: gemfiles/mongoid3.gemfile
notifications:
  recipients:
    - andreas@aloop.org
